=== sivvy/jenkins-mobile-phonegap-winktoolkit/assets/www/libs/wink/utils/doc/wink_doc.dtd
<!ELEMENT module ( title, name, is_graphical, description, test_pages?, compatibility, dependencies?, instanciation, components, styles? ) >

<!ELEMENT test_pages ( page+ ) >
<!ELEMENT page ( description, url ) >

<!ELEMENT dependencies ( dependency+ ) >
<!ELEMENT dependency ( module_name ) >

<!ELEMENT instanciation ( description, properties*, code_sample ) >

<!ELEMENT components ( component+ ) >
<!ELEMENT component ( name, description, public_methods*, public_properties*, events* ) >

<!ELEMENT public_methods ( method+ ) >
<!ELEMENT method ( name, description, parameters? ) >

<!ELEMENT parameters ( parameter+ ) >
<!ELEMENT parameter ( name, description, type, is_optional ) >

<!ELEMENT public_properties ( property+ ) >

<!ELEMENT properties ( property+ ) >
<!ELEMENT property ( name, description, type, is_optional? ) >

<!ELEMENT events ( event+ ) >
<!ELEMENT event ( name, description, return? ) >

<!ELEMENT return ( property+ ) >

<!ELEMENT styles ( classes ) >
<!ELEMENT classes ( class+ ) >
<!ELEMENT class ( name, description ) >

<!ELEMENT code_sample ( #PCDATA ) >
<!ELEMENT compatibility ( #PCDATA ) >
<!ELEMENT description ( #PCDATA ) >
<!ELEMENT is_graphical ( #PCDATA ) >
<!ELEMENT is_optional ( #PCDATA ) >
<!ELEMENT module_name ( #PCDATA ) >
<!ELEMENT name ( #PCDATA ) >
<!ELEMENT title ( #PCDATA ) >
<!ELEMENT type ( #PCDATA ) >
<!ELEMENT url ( #PCDATA ) >

=== sivvy/jenkins-mobile-phonegap-winktoolkit/assets/www/libs/wink/ui/layout/fixedlayout/doc/fixedlayout.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//WAPFORUM//DTD XHTML Mobile 1.0//EN" "../../../../utils/doc/wink_doc.dtd" >
<?xml-stylesheet type="text/xsl" href="../../../../utils/doc/wink_doc.xsl"?>
<module>
  <title>Fixed layout</title>
  <name>wink.ui.layout.FixedLayout</name>
  <is_graphical>0</is_graphical>
  <description>
    The Fixed layout implements a layout with "fixed" header and/or footer. 
    There are two implementations depending on whether the fixed position is supported.
    If it is supported, then it is a native behavior that does not include public property.
  </description>
  <test_pages>
    <page>
      <description>This test shows a layout with a header and a footer bar.</description>
      <url>test_fixedlayout.html</url>
    </page>
    <page>
      <description>A variant with semi-transparent bars.</description>
      <url>test_fixedlayout2.html</url>
    </page>
  </test_pages>
  <compatibility>Iphone OS2 (slow), Iphone OS3, Iphone OS4, Android 1.5, Android 2.1, Android 2.2, Android 2.3, BlackBerry 6, Bada 1.0</compatibility>
  <dependencies>
    <dependency>
      <module_name>wink.ux.window</module_name>
    </dependency>
  </dependencies>
  <instanciation>
    <description></description>
    <properties>
      <property>
        <name>target</name>
        <description>The target node identifier</description>
        <type>string</type>
        <is_optional>0</is_optional>
      </property>
      <property>
        <name>header</name>
        <description>The header node identifier</description>
        <type>string</type>
        <is_optional>1</is_optional>
      </property>
      <property>
        <name>footer</name>
        <description>The footer node identifier</description>
        <type>string</type>
        <is_optional>1</is_optional>
      </property>
      <property>
        <name>nativeFixed</name>
        <description>false to enable the default implementation even if the fixed positioning is supported</description>
        <type>boolean</type>
        <is_optional>1</is_optional>
      </property>
      <property>
        <name>displayDuration</name>
        <description>the duration of the opacity transition when bars appear (default: 0)</description>
        <type>integer</type>
        <is_optional>1</is_optional>
      </property>
      <property>
        <name>moveDuration</name>
        <description>the duration of the top transition when bars are partially visible (cut) (default: 0)</description>
        <type>integer</type>
        <is_optional>1</is_optional>
      </property>
      <property>
        <name>preventTouchBar</name>
        <description>prevents from moving the bars with touch (default: true)</description>
        <type>boolean</type>
        <is_optional>1</is_optional>
      </property>
      <property>
        <name>activated</name>
        <description>indicates if the layout is activated (default: true)</description>
        <type>boolean</type>
        <is_optional>1</is_optional>
      </property>
      <property>
        <name>showHideOnClick</name>
        <description>allows to show / hide the bars on click (default: false)</description>
        <type>boolean</type>
        <is_optional>1</is_optional>
      </property>
      <property>
        <name>urlBarShorcutHeight</name>
        <description>used when a shortcut is displayed for the url bar (default: 0)</description>
        <type>integer</type>
        <is_optional>1</is_optional>
      </property>
      <property>
        <name>scrollAtStart</name>
        <description>Indicates if the component needs to listen the start event in order to hide bars properly (default: 0)</description>
        <type>boolean</type>
        <is_optional>1</is_optional>
      </property>
    </properties>
    <code_sample>
var properties = 
{
	target: 'targetElementId',
	header: 'headerElementId',
	footer: 'footerElementId'
};
fixedlayout = new wink.ui.layout.FixedLayout(properties);
    </code_sample>
  </instanciation>
  <components>
    <component>
      <name>wink.ui.layout.FixedLayout</name>
      <description>The Fixed layout component</description>
      <public_methods>
        <method>
          <name>enable</name>
          <description>Enables the bars position updates</description>
        </method>
        <method>
          <name>disable</name>
          <description>Disables the bars position updates</description>
        </method>
        <method>
          <name>getPosition</name>
          <description>Returns the current y position</description>
        </method>
        <method>
          <name>scrollTo</name>
          <description>Scroll explicitly to the given position</description>
          <parameters>
            <parameter>
              <name>y</name>
              <description>The y targeted coordinates</description>
              <type>integer</type>
              <is_optional>0</is_optional>
            </parameter>
          </parameters>
        </method>
        <method>
          <name>refreshView</name>
          <description>Refresh the view. This can be useful after a change of view.</description>
        </method>
      </public_methods>
      <public_properties>
        <property>
          <name>uId</name>
          <description>The unique identifier of the component.</description>
          <type>integer</type>
        </property>
        <property>
          <name>displayDuration</name>
          <description>see instanciation</description>
          <type>integer</type>
        </property>
        <property>
          <name>moveDuration</name>
          <description>see instanciation</description>
          <type>integer</type>
        </property>
        <property>
          <name>preventTouchBar</name>
          <description>see instanciation</description>
          <type>integer</type>
        </property>
        <property>
          <name>activated</name>
          <description>see instanciation</description>
          <type>boolean</type>
        </property>
      </public_properties>
    </component>
  </components>
</module>

=== sivvy/jenkins-mobile-phonegap-winktoolkit/assets/www/libs/wink/ux/search/doc/search.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//WAPFORUM//DTD XHTML Mobile 1.0//EN" "../../../utils/doc/wink_doc.dtd" >
<?xml-stylesheet type="text/xsl" href="../../../utils/doc/wink_doc.xsl"?>
<module>
  <title>Search</title>
  <name>wink.ux.Search</name>
  <is_graphical>0</is_graphical>
  <description>The search object allows you to process searches in an HTML document and browse search results. </description>
  <test_pages>
    <page>
      <description>Displays the Obama wikipedia page. Type your search into the top input and click on the 'OK' button of the Iphone virtual keyboard to see the results of your search. Click the 'previous' and 'next' buttons to navigate through the results</description>
      <url>test_search_scroller.html</url>
    </page>
  </test_pages>
  <compatibility>Iphone OS2, Iphone OS3, Iphone OS4, Android 1.1, Android 1.5, Android 2.1, Android 2.2, Android 2.3, BlackBerry 6, Bada 1.0</compatibility>
  <instanciation>
    <description>To instantiate the search component, you need to provide the DOM node where the search should be performed, the results classname and a classname for the selected results</description>
    <properties>
      <property>
        <name>textNode</name>
        <description>DOM node containing the text to search in</description>
        <type>DOM node</type>
        <is_optional>0</is_optional>
      </property>
      <property>
        <name>resultClassName</name>
        <description>CSS class to apply to search results. This class has to be defined by the developer</description>
        <type>string</type>
        <is_optional>0</is_optional>
      </property>
      <property>
        <name>resultSelectClassName</name>
        <description>CSS class to apply to the currently selected search result. This class has to be defined by the developer</description>
        <type>string</type>
        <is_optional>0</is_optional>
      </property>
    </properties>
    <code_sample>
var searchProperties = 
{
	textNode: $("moveable"),
	resultClassName: "surligne",
	resultSelectClassName: "surligneSelect"
}

search = new wink.ux.Search(searchProperties);
    </code_sample>
  </instanciation>
  <components>
    <component>
      <name>wink.ux.Search</name>
      <description>Process the document and search for strings</description>
      <public_methods>
        <method>
          <name>search</name>
          <description>processes a search in the considered HTML node. Applies the adequate CSS class to results and selects first result</description>
          <parameters>
            <parameter>
              <name>s</name>
              <description>the text to search in textNode</description>
              <type>string</type>
              <is_optional>0</is_optional>
            </parameter>
          </parameters>
        </method>
        <method>
          <name>reset</name>
          <description>resets the considered HTML node (replaces its content by the original content)</description>
        </method>
        <method>
          <name>next</name>
          <description>selects next result</description>
        </method>
        <method>
          <name>previous</name>
          <description>selects previous result</description>
        </method>
      </public_methods>
      <public_properties>
        <property>
          <name>uId</name>
          <description>unique identifier of the component</description>
          <type>integer</type>
        </property>
        <property>
          <name>totalResults</name>
          <description>number of search results</description>
          <type>integer</type>
        </property>
        <property>
          <name>currentResult</name>
          <description>index of the currently selected result (from 1 to totalResults)</description>
          <type>integer</type>
        </property>
      </public_properties>
    </component>
  </components>
</module>

=== sivvy/jenkins-mobile-phonegap-winktoolkit/assets/www/libs/wink/ui/xy/progressbar/doc/progressbar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//WAPFORUM//DTD XHTML Mobile 1.0//EN" "../../../../utils/doc/wink_doc.dtd" >
<?xml-stylesheet type="text/xsl" href="../../../../utils/doc/wink_doc.xsl"?>
<module>
  <title>Progress Bar</title>
  <name>wink.ui.xy.ProgressBar</name>
  <is_graphical>1</is_graphical>
  <description>Creates an animated progress bar</description>
  <test_pages>
    <page>
      <description>2 progress bars are displayed and the progress is updated by a timer every 800ms.</description>
      <url>test_progressbar</url>
    </page>
  </test_pages>
  <compatibility>Iphone OS2, Iphone OS3, Iphone OS4, Android 1.1, Android 1.5, Android 2.1, Android 2.2, Android 2.3, BlackBerry 6, Bada 1.0</compatibility>
  <instanciation>
    <description>When you instantiate a new progressbar, you can pass different parameters in order to configure the look and feel of the bar. Use the 'getDomNode' method to add the progress bar to the page.</description>
    <properties>
      <property>
        <name>value</name>
        <description>The initial value of the progress bar</description>
        <type>integer</type>
        <is_optional>1</is_optional>
      </property>
      <property>
        <name>height</name>
        <description>The height in pixels of the bar. The default value is 5px</description>
        <type>integer</type>
        <is_optional>1</is_optional>
      </property>
      <property>
        <name>width</name>
        <description>The width in pixels of the bar. The default value is 200px</description>
        <type>integer</type>
        <is_optional>1</is_optional>
      </property>
      <property>
        <name>borderColor</name>
        <description>The border color of the progress bar. It can be either 'transparent' or the hexa code of the color. The default value is #ff0000</description>
        <type>string</type>
        <is_optional>1</is_optional>
      </property>
      <property>
        <name>progressBarColor</name>
        <description>The color of the progress bar background. It can be either 'transparent' or the hexa code of the color. The default value is #ff5500</description>
        <type>string</type>
        <is_optional>1</is_optional>
      </property>
      <property>
        <name>progressBarImage</name>
        <description>Add a background image instead of a background color to the bar. The 'progressBarImage' is an object the contains the 'image' (the image encoded in base64) and the 'type' of the image (e.g.: gif, png). See the test page for more details.</description>
        <type>object</type>
        <is_optional>1</is_optional>
      </property>
    </properties>
    <code_sample>
var properties =
{
	'height': 5,
	'width' : 200,
	'borderColor': '#000',
	'progressBarColor': '#ff0000',
}

progressBar = new wink.ui.xy.ProgressBar(properties);
		
$('output').appendChild(progressBar.getDomNode());
	</code_sample>
  </instanciation>
  <components>
    <component>
      <name>wink.ui.xy.ProgressBar</name>
      <description>Creates the progress bar and handle the progress</description>
      <public_methods>
        <method>
          <name>setValue</name>
          <description>Set the current value of the progress bar (between 0 and 100) and update the progress display</description>
          <parameters>
            <parameter>
              <name>value</name>
              <description>The value in percentage (between 0 and 100) of the progress bar</description>
              <type>integer</type>
              <is_optional>0</is_optional>
            </parameter>
          </parameters>
        </method>
        <method>
          <name>setBorderColor</name>
          <description>Change the border color of the progress bar</description>
          <parameters>
            <parameter>
              <name>color</name>
              <description>The border color of the progress bar. It can be either 'transparent' or the hexa code of the color.</description>
              <type>string</type>
              <is_optional>0</is_optional>
            </parameter>
          </parameters>
        </method>
        <method>
          <name>setProgressBarColor</name>
          <description>Change the color of the progress bar background</description>
          <parameters>
            <parameter>
              <name>color</name>
              <description>The background color of the progress bar. It can be either 'transparent' or the hexa code of the color.</description>
              <type>string</type>
              <is_optional>0</is_optional>
            </parameter>
          </parameters>
        </method>
        <method>
          <name>setProgressBarImage</name>
          <description>Change the background image of the progress bar</description>
          <parameters>
            <parameter>
              <name>image</name>
              <description>An object that contains the 'image' (the image encoded in base64) and the 'type' of the image (e.g.: gif, png)</description>
              <type>object</type>
              <is_optional>0</is_optional>
            </parameter>
          </parameters>
        </method>
        <method>
          <name>getDomNode</name>
          <description>returns the DOM node containing the progress bar</description>
        </method>
      </public_methods>
      <public_properties>
        <property>
          <name>uId</name>
          <description>unique identifier of the component</description>
          <type>integer</type>
        </property>
        <property>
          <name>value</name>
          <description>the current value of the progress bar</description>
          <type>integer</type>
        </property>
        <property>
          <name>height</name>
          <description>the height in pixels of the progress bar</description>
          <type>integer</type>
        </property>
        <property>
          <name>width</name>
          <description>the width in pixels of the progress bar</description>
          <type>integer</type>
        </property>
        <property>
          <name>borderColor</name>
          <description>the border color of the progress bar</description>
          <type>string</type>
        </property>
        <property>
          <name>progressBarColor</name>
          <description>the color of the progress bar background</description>
          <type>string</type>
        </property>
        <property>
          <name>progressBarImage</name>
          <description>the progress bar background image</description>
          <type>object</type>
        </property>
      </public_properties>
      <events>
        <event>
          <name>/progressbar/events/end</name>
          <description>This event is fired when the progress bar reaches 100%</description>
        </event>
      </events>
    </component>
  </components>
</module>

=== sivvy/jenkins-mobile-phonegap-winktoolkit/assets/www/libs/wink/ui/layout/slidingpanels/doc/slidingpanels.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//WAPFORUM//DTD XHTML Mobile 1.0//EN" "../../../../utils/doc/wink_doc.dtd" >
<?xml-stylesheet type="text/xsl" href="../../../../utils/doc/wink_doc.xsl"?>
<module>
  <title>Sliding panels</title>
  <name>wink.ui.layout.SlidingPanels</name>
  <is_graphical>1</is_graphical>
  <description>Create a sliding panels container container with which you can navigate through pages with an Iphone like UX</description>
  <test_pages>
    <page>
      <description>The sliding panels container contains 8 pages. Click on the texts in the pages to go to the next page or go to another page or go back to the previous page.</description>
      <url>test_slidingpanels.html</url>
    </page>
    <page>
      <description>The same test page as test_slidingpanels.html but with a 'cover' transition</description>
      <url>test_slidingpanels_cover.html</url>
    </page>
    <page>
      <description>The same test page as test_slidingpanels.html but with a 'reveal' transition</description>
      <url>test_slidingpanels_reveal.html</url>
    </page>
    <page>
      <description>The same test page as test_slidingpanels.html but it also integrates the History component. You can navigate using the 'back' and 'forward' buttons of your browser</description>
      <url>test_slidingpanels_with_history.html</url>
    </page>
  </test_pages>
  <compatibility>Iphone OS2, Iphone OS3, Iphone OS4, Android 1.5, Android 2.1, Android 2.2, Android 2.3, BlackBerry 6, Bada 1.0</compatibility>
  <instanciation>
    <description>To instantiate a sliding panels container, the pages (dom nodes) MUST already be present in the page and each one MUST be defined by a unique id. Use the 'getDomNode' method to add the sliding panels container into the page.</description>
    <properties>
      <property>
        <name>duration</name>
        <description>The slide duration in milliseconds. The default value is 800</description>
        <type>integer</type>
        <is_optional>1</is_optional>
      </property>
      <property>
        <name>transitionType</name>
        <description>the type of the transition between pages ('default', 'cover' or 'reveal'). If you use the 'cover' or 'reveal' option, all your pages should have the same height</description>
        <type>string</type>
        <is_optional>1</is_optional>
      </property>
      <property>
        <name>pages</name>
        <description>An array containing the ids of the pages to add into the sliding panels container. The pages dom nodes MUST be present in the page at instantiation time.</description>
        <type>array</type>
        <is_optional>0</is_optional>
      </property>
    </properties>
    <code_sample>
var properties = 
{
	'duration': 500,
	'transitionType': 'default',
	'pages': ['page1', 'page2', 'page3', 'page4', 'page5', 'page6', 'page7', 'page8']
}

slidingPanels = new wink.ui.layout.SlidingPanels(properties);

document.body.appendChild(slidingPanels.getDomNode());
    </code_sample>
  </instanciation>
  <components>
    <component>
      <name>wink.ui.layout.SlidingPanels</name>
      <description>Create the sliding panels container, creates pages and handle the animation of the pages</description>
      <public_methods>
        <method>
          <name>slideTo</name>
          <description>Move to the selected page</description>
          <parameters>
            <parameter>
              <name>id</name>
              <description>the id of the page to display</description>
              <type>string</type>
              <is_optional>0</is_optional>
            </parameter>
          </parameters>
        </method>
        <method>
          <name>slideBack</name>
          <description>Come back to the previous page</description>
        </method>
        <method>
          <name>getDomNode</name>
          <description>returns the DOM node containing the slidingpanels</description>
        </method>
      </public_methods>
      <public_properties>
        <property>
          <name>uId</name>
          <description>unique identifier of the component</description>
          <type>integer</type>
        </property>
        <property>
          <name>duration</name>
          <description>the slide duration</description>
          <type>integer</type>
        </property>
        <property>
          <name>transitionType</name>
          <description>the type of the transition between pages</description>
          <type>string</type>
        </property>
        <property>
          <name>pages</name>
          <description>the list of pages ids of the slidingpanels</description>
          <type>array</type>
        </property>
      </public_properties>
      <events>
        <event>
          <name>/slidingpanels/events/slidestart</name>
          <description>fired when a slide starts</description>
          <return>
            <property>
              <name>id</name>
              <description>the id of the current page</description>
              <type>string</type>
            </property>
          </return>
        </event>
        <event>
          <name>/slidingpanels/events/slideend</name>
          <description>fired when a slide ends</description>
          <return>
            <property>
              <name>id</name>
              <description>the id of the current page</description>
              <type>string</type>
            </property>
          </return>
        </event>
      </events>
    </component>
    <component>
      <name>wink.ui.layout.SlidingPanels.Page</name>
      <description>Create a page. Pages should only be instantiated by the slidingpanels object</description>
      <public_methods>
        <method>
          <name>setPosition</name>
          <description>set the current position of the page</description>
          <parameters>
            <parameter>
              <name>position</name>
              <description>-1: page is on the left ; 0: page is displayed ; 1: page is on the right</description>
              <type>integer</type>
              <is_optional>0</is_optional>
            </parameter>
          </parameters>
        </method>
        <method>
          <name>getDomNode</name>
          <description>returns the DOM node containing the page</description>
        </method>
        <method>
          <name>display</name>
          <description>Display the page</description>
        </method>
        <method>
          <name>translate</name>
          <description>translate the page</description>
          <parameters>
            <parameter>
              <name>x</name>
              <description>the translate distance</description>
              <type>string/integer</type>
              <is_optional>0</is_optional>
            </parameter>
          </parameters>
        </method>
        <method>
          <name>setZIndex</name>
          <description>Set the z-index of the page</description>
          <parameters>
            <parameter>
              <name>z</name>
              <description>the index to set</description>
              <type>integer</type>
              <is_optional>0</is_optional>
            </parameter>
          </parameters>
        </method>
        <method>
          <name>setTranslateDuration</name>
          <description>Set the translation duration of the page</description>
          <parameters>
            <parameter>
              <name>d</name>
              <description>the duration</description>
              <type>string</type>
              <is_optional>0</is_optional>
            </parameter>
          </parameters>
        </method>
      </public_methods>
      <public_properties>
        <property>
          <name>uId</name>
          <description>unique identifier of the component</description>
          <type>integer</type>
        </property>
        <property>
          <name>id</name>
          <description>the dom node id of the page</description>
          <type>string</type>
        </property>
        <property>
          <name>position</name>
          <description>the position of the page (-1: page is on the left ; 0: page is displayed ; 1: page is on the right)</description>
          <type>integer</type>
        </property>
      </public_properties>
    </component>
  </components>
  <styles>
    <classes>
      <class>
        <name>sl_container</name>
        <description>The main container of the SlidingPanels object</description>
      </class>
      <class>
        <name>sl_page</name>
        <description>The class added to the pages of the SlidingPanels object</description>
      </class>
    </classes>
  </styles>
</module>
