=== sivvy/jenkins-mobile-phonegap-winktoolkit/assets/www/libs/wink/utils/doc/wink_doc.dtd
<!ELEMENT module ( title, name, is_graphical, description, test_pages?, compatibility, dependencies?, instanciation, components, styles? ) >

<!ELEMENT test_pages ( page+ ) >
<!ELEMENT page ( description, url ) >

<!ELEMENT dependencies ( dependency+ ) >
<!ELEMENT dependency ( module_name ) >

<!ELEMENT instanciation ( description, properties*, code_sample ) >

<!ELEMENT components ( component+ ) >
<!ELEMENT component ( name, description, public_methods*, public_properties*, events* ) >

<!ELEMENT public_methods ( method+ ) >
<!ELEMENT method ( name, description, parameters? ) >

<!ELEMENT parameters ( parameter+ ) >
<!ELEMENT parameter ( name, description, type, is_optional ) >

<!ELEMENT public_properties ( property+ ) >

<!ELEMENT properties ( property+ ) >
<!ELEMENT property ( name, description, type, is_optional? ) >

<!ELEMENT events ( event+ ) >
<!ELEMENT event ( name, description, return? ) >

<!ELEMENT return ( property+ ) >

<!ELEMENT styles ( classes ) >
<!ELEMENT classes ( class+ ) >
<!ELEMENT class ( name, description ) >

<!ELEMENT code_sample ( #PCDATA ) >
<!ELEMENT compatibility ( #PCDATA ) >
<!ELEMENT description ( #PCDATA ) >
<!ELEMENT is_graphical ( #PCDATA ) >
<!ELEMENT is_optional ( #PCDATA ) >
<!ELEMENT module_name ( #PCDATA ) >
<!ELEMENT name ( #PCDATA ) >
<!ELEMENT title ( #PCDATA ) >
<!ELEMENT type ( #PCDATA ) >
<!ELEMENT url ( #PCDATA ) >

=== sivvy/jenkins-mobile-phonegap-winktoolkit/libs/wink/ui/xy/datepicker/doc/datepicker.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//WAPFORUM//DTD XHTML Mobile 1.0//EN" "../../../../utils/doc/wink_doc.dtd" >
<?xml-stylesheet type="text/xsl" href="../../../../utils/doc/wink_doc.xsl"?>
<module>
  <title>Date picker</title>
  <name>wink.ui.xy.DatePicker</name>
  <is_graphical>1</is_graphical>
  <description>Displays a calendar. The user can select a date by clicking on a day.</description>
  <test_pages>
    <page>
      <description>Click on the 'show calendar' button to display the date picker. When the user selects a day, it will be displayed in the input field next to the button.</description>
      <url>test_datepicker.html</url>
    </page>
  </test_pages>
  <compatibility>Iphone OS2, Iphone OS3, Iphone OS4, Android 1.1, Android 1.5, Android 2.1, Android 2.2, Android 2.3, BlackBerry 6, Bada 1.0</compatibility>
  <instanciation>
    <description>The DatePicker is a singleton, it needs to be instantiated only once. No parameter is needed. To display the date picker, call the 'show' method. To be informed of a date pick, the application must listen to the '/datepicker/events/pickdate' event.</description>
    <code_sample>
datepicker = new wink.ui.xy.DatePicker();
 	
datepicker.show();
    </code_sample>
  </instanciation>
  <components>
    <component>
      <name>wink.ui.xy.DatePicker</name>
      <description>Create the date picker DOM node and fires events when a date is selected</description>
      <public_methods>
        <method>
          <name>show</name>
          <description>display the date picker</description>
        </method>
        <method>
          <name>hide</name>
          <description>hide the date picker</description>
        </method>
        <method>
          <name>updatePosition</name>
          <description>update the position of the date picker and places it at the center of the page</description>
        </method>
      </public_methods>
      <public_properties>
        <property>
          <name>uId</name>
          <description>The unique identifier of the component</description>
          <type>integer</type>
        </property>
      </public_properties>
      <events>
        <event>
          <name>/datepicker/events/pickdate</name>
          <description>The user clicked on a date</description>
          <return>
            <property>
              <name>date</name>
              <description>the JavaScript Date object representing the day on which the user clicked</description>
              <type>object</type>
            </property>
          </return>
        </event>
      </events>
    </component>
  </components>
  <styles>
    <classes>
      <class>
        <name>dp_datepicker</name>
        <description>The class of the date picker</description>
      </class>
      <class>
        <name>dp_navigation</name>
        <description>The class of the navigation system (to navigate through months)</description>
      </class>
      <class>
        <name>dp_previous</name>
        <description>The class of the 'previous' arrow</description>
      </class>
      <class>
        <name>dp_next</name>
        <description>The class of the 'next' arrow</description>
      </class>
      <class>
        <name>dp_month</name>
        <description>The class of the month display</description>
      </class>
      <class>
        <name>dp_days_container</name>
        <description>The class for the section containing the days of the week</description>
      </class>
      <class>
        <name>dp_days</name>
        <description>The class for a day of the week</description>
      </class>
      <class>
        <name>dp_dates_container</name>
        <description>The class for the section containing the days numbers</description>
      </class>
      <class>
        <name>dp_date</name>
        <description>The class for a date</description>
      </class>
      <class>
        <name>dp_today</name>
        <description>The class for the current day</description>
      </class>
      <class>
        <name>dp_finished</name>
        <description>The class for the days which are over</description>
      </class>
    </classes>
  </styles>
</module>

=== sivvy/jenkins-mobile-phonegap-winktoolkit/assets/www/libs/wink/mm/mediawheel/doc/mediawheel.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//WAPFORUM//DTD XHTML Mobile 1.0//EN" "../../../utils/doc/wink_doc.dtd" >
<?xml-stylesheet type="text/xsl" href="../../../utils/doc/wink_doc.xsl"?>
<module>
  <title>Media wheel</title>
  <name>wink.mm.MediaWheel</name>
  <is_graphical>1</is_graphical>
  <description>The media wheel is a progress bar, displayed as a wheel, used for media files and based on the Canvas tag</description>
    <test_pages>
    <page>
      <description>This test page associates a media wheel with an audio tag.</description>
      <url>test_mediawheel.html</url>
    </page>
    <page>
      <description>This test page associates a media wheel with a video tag.</description>
      <url>test_mediawheel2.html</url>
    </page>
  </test_pages>
  <compatibility>Iphone OS4, Ipad</compatibility>
  <dependencies>
    <dependency>
      <module_name>wink.math._geometric</module_name>
    </dependency>
    <dependency>
      <module_name>wink.ux.MovementTracker</module_name>
    </dependency>
  </dependencies>
  <instanciation>
    <description>The audio player can take several parameters. It takes at least the width and height parameters. Use the getDomNode method to add the component to the page</description>
    <properties>
      <property>
        <name>width</name>
        <description>the width of the container</description>
        <type>integer</type>
        <is_optional>0</is_optional>
      </property>
      <property>
        <name>height</name>
        <description>the height of the container</description>
        <type>integer</type>
        <is_optional>0</is_optional>
      </property>
      <property>
        <name>radius</name>
        <description>the radius of the wheel</description>
        <type>integer</type>
        <is_optional>1</is_optional>
      </property>
      <property>
        <name>thickness</name>
        <description>the thickness of the wheel</description>
        <type>integer</type>
        <is_optional>1</is_optional>
      </property>
      <property>
        <name>startAngle</name>
        <description>the start angle of the wheel</description>
        <type>integer</type>
        <is_optional>1</is_optional>
      </property>
      <property>
        <name>endAngle</name>
        <description>the end angle of the wheel</description>
        <type>integer</type>
        <is_optional>1</is_optional>
      </property>
      <property>
        <name>readGradientColors</name>
        <description>the gradient colors of the read part of the media (eg. [{ pos: 0, color: color1 },{ pos: 0.75, color: color2 },{ pos: 1, color: color3 }])</description>
        <type>array</type>
        <is_optional>1</is_optional>
      </property>
      <property>
        <name>bgGradientColors</name>
        <description>the gradient colors of the background part of the media (eg. [{ pos: 0, color: color1 },{ pos: 0.75, color: color2 },{ pos: 1, color: color3 }])</description>
        <type>array</type>
        <is_optional>1</is_optional>
      </property>
      <property>
        <name>unbufferedGradientColors</name>
        <description>the gradient colors of the unbuffered part of the media (eg. [{ pos: 0, color: color1 },{ pos: 0.75, color: color2 },{ pos: 1, color: color3 }])</description>
        <type>array</type>
        <is_optional>1</is_optional>
      </property>
      <property>
        <name>cursorRectColor</name>
        <description>the color of the cursor's rectangle</description>
        <type>string</type>
        <is_optional>1</is_optional>
      </property>
      <property>
        <name>cursorTriangleColor</name>
        <description>the color of the cursor's triangle</description>
        <type>string</type>
        <is_optional>1</is_optional>
      </property>
      <property>
        <name>canChangeTime</name>
        <description>indicates whether the user can change the time by moving or clicking on the wheel (default is true)</description>
        <type>boolean</type>
        <is_optional>1</is_optional>
      </property>
    </properties>
    <code_sample>
var mediaWheel = new wink.mm.MediaWheel({
  width: $('content').offsetWidth,
  height: $('content').offsetHeight
});

$('content').appendChild(mediaWheel.getDomNode());
    </code_sample>
  </instanciation>
  <components>
    <component>
      <name>wink.mm.MediaWheel</name>
      <description>the Media player</description>
      <public_methods>
        <method>
          <name>getDomNode</name>
          <description>Returns the DOM node of the component</description>
        </method>
        <method>
          <name>setDuration</name>
          <description>Set the duration</description>
          <parameters>
            <parameter>
              <name>duration</name>
              <description>the duration</description>
              <type>real</type>
              <is_optional>0</is_optional>
            </parameter>
          </parameters>
        </method>
        <method>
          <name>setTime</name>
          <description>Set the time</description>
          <parameters>
            <parameter>
              <name>time</name>
              <description>the time</description>
              <type>real</type>
              <is_optional>0</is_optional>
            </parameter>
          </parameters>
        </method>
        <method>
          <name>setBufferedTime</name>
          <description>Set the buffered time</description>
          <parameters>
            <parameter>
              <name>buftime</name>
              <description>the buffered time</description>
              <type>real</type>
              <is_optional>0</is_optional>
            </parameter>
          </parameters>
        </method>
      </public_methods>
      <public_properties>
        <property>
          <name>uId</name>
          <description>unique identifier of the component</description>
          <type>integer</type>
        </property>
      </public_properties>
      <events>
        <event>
          <name>/mediawheel/events/timeupdate</name>
          <description>the time is updated by the user</description>
        </event>
      </events>
    </component>
  </components>
  <styles>
    <classes>
      <class>
        <name>mw_container</name>
        <description>the main DOM node of the component</description>
      </class>
    </classes>
  </styles>
</module>

=== sivvy/jenkins-mobile-phonegap-winktoolkit/assets/www/libs/wink/api/geolocation/doc/geolocation.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//WAPFORUM//DTD XHTML Mobile 1.0//EN" "../../../utils/doc/wink_doc.dtd" >
<?xml-stylesheet type="text/xsl" href="../../../utils/doc/wink_doc.xsl"?>
<module>
  <title>GeoLocation</title>
  <name>wink.api.GeoLocation</name>
  <is_graphical>0</is_graphical>
  <description>
  	GeoLocation is a geographical locator. It starts watching for position changes when a listener is 
  	adding and stops if there is no more listener. To optimize the data processing, it gets the stringent 
  	constraints (depends on listeners properties) which requires it to refresh datas more often and more 
  	precisely. Then it notifies listeners when it is deemed necessary 
  	(depends on listeners properties : "notification interval", "only If Position Changed").
  </description>
  <test_pages>
    <page>
      <description>
      	This test page implements a GeoLocation and 3 listeners :
      	 - the first is notified every 5 seconds of the current position
      	 - the second is notified every 10 seconds of the current position
      	 - the third is notified every 1 second only if the position has changed
      	The information are displays in panels associated to listeners.
      	A checkbox allows the user to enable or disable the "high accuracy" of results.
      	Obviously, this test is significant when the device moves.
      </description>
      <url>test_geolocation.html</url>
    </page>
  </test_pages>
  <compatibility>Iphone OS2, Iphone OS3, Iphone OS4, Android 1.1, Android 1.5, Android 2.1, Android 2.2, Android 2.3</compatibility>
  <instanciation>
    <description>The GeoLocation is a singleton, it needs to be instantiated only once. It does not need parameters, its behavior is dependent on active listeners.</description>
    <code_sample>
var winkgeoloc = new wink.api.GeoLocation();
winkgeoloc.addListener({ context: window, method: "accuratePositionChanged" }, 60000, true, true);
winkgeoloc.addListener({ context: window, method: "positionChanged" }, 10000, true, false);
    </code_sample>
  </instanciation>
  <components>
    <component>
      <name>wink.api.GeoLocation</name>
      <description>The GeoLocation component</description>
      <public_methods>
        <method>
          <name>addListener</name>
          <description>Adds a Geo Location listener</description>
          <parameters>
            <parameter>
              <name>callback</name>
              <description>The callback to invoke : { context, method, arguments }</description>
              <type>object</type>
              <is_optional>0</is_optional>
            </parameter>
            <parameter>
              <name>notificationInterval</name>
              <description>The interval between callback calls (in millisecond)</description>
              <type>integer</type>
              <is_optional>0</is_optional>
            </parameter>
            <parameter>
              <name>onlyIfPositionChanged</name>
              <description>Indicates whether the callback must be invoked only if location changed</description>
              <type>boolean</type>
              <is_optional>0</is_optional>
            </parameter>
            <parameter>
              <name>highAccuracy</name>
              <description>Indicates whether the high result accuracy is enabled</description>
              <type>boolean</type>
              <is_optional>0</is_optional>
            </parameter>
          </parameters>
        </method>
        <method>
          <name>removeListener</name>
          <description>Removes the given Geo Location listener</description>
          <parameters>
            <parameter>
              <name>callback</name>
              <description>The callback that was previously added (identified by { context, method })</description>
              <type>object</type>
              <is_optional>0</is_optional>
            </parameter>
          </parameters>
        </method>
        <method>
          <name>getPosition</name>
          <description>Returns the current geolocation informations or null if the component is not initialized. At least one listener must be added to initialize the component.</description>
        </method>
      </public_methods>
      <public_properties>
        <property>
          <name>uId</name>
          <description>The unique identifier of the component.</description>
          <type>integer</type>
        </property>
      </public_properties>
    </component>
  </components>
</module>

=== sivvy/jenkins-mobile-phonegap-winktoolkit/assets/www/libs/wink/ux/gesture/doc/gesture.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//WAPFORUM//DTD XHTML Mobile 1.0//EN" "../../../utils/doc/wink_doc.dtd" >
<?xml-stylesheet type="text/xsl" href="../../../utils/doc/wink_doc.xsl"?>
<module>
  <title>Gesture</title>
  <name>wink.ux.gesture</name>
  <is_graphical>0</is_graphical>
  <description>
  	The gesture object is able to determines whether some gestures (with exactly 2 fingers) 
  	are performed on the nodes and if so, inform the listeners. Gestures that can be listened 
  	are : 
  	 - two_digits_click: on click with 2 fingers
  	 - two_digits_press: on pressure with 2 fingers
  	 - enlargement: A separation of the 2 fingers, as if to zoom in
  	 - narrowing: bring 2 fingers closer, as if to zoom out
  	 - rotation: a rotation with 2 fingers
  	 - instant_scale: Each alignment or each spacing of 2 fingers
  	 - instant_rotation: Each rotation of 2 fingers
  	 - gesture_end: the end a a gesture
  	The notifications to the listeners include parameters that depends on gesture type.
  </description>
  <test_pages>
    <page>
      <description>A full test of each gesture on 2 separated nodes.</description>
      <url>test_gesture.html</url>
    </page>
    <page>
      <description>A square which can be rotated, expanded and shrunk.</description>
      <url>test_gesture_box.html</url>
    </page>
  </test_pages>
  <compatibility>Iphone OS2, Iphone OS3, Iphone OS4</compatibility>
  <instanciation>
    <description>The gesture object is a Literal, so it did not need to be instantiated.</description>
    <code_sample>
var node = $("nodeId");
wink.ux.gesture.listenTo(node, "two_digits_click", { context: window, method: "twoDigitsClick" }, { preventDefault: true });
    </code_sample>
  </instanciation>
  <components>
    <component>
      <name>wink.ux.gesture</name>
      <description>The gesture component</description>
      <public_methods>
        <method>
          <name>listenTo</name>
          <description>Allows to listen for a specific gesture on a dom Node.</description>
          <parameters>
            <parameter>
              <name>domNode</name>
              <description>the DOM node that listens to gesture</description>
              <type>DOM node</type>
              <is_optional>0</is_optional>
            </parameter>
            <parameter>
              <name>gesture</name>
              <description>The gesture name to listen</description>
              <type>string</type>
              <is_optional>0</is_optional>
            </parameter>
            <parameter>
              <name>callback</name>
              <description>The callback to invoke when the gesture id done : { context, method, arguments }</description>
              <type>object</type>
              <is_optional>0</is_optional>
            </parameter>
            <parameter>
              <name>options</name>
              <description>The options associated to the listener: { preventDefault: Indicates whether an automatic preventDefault must be done (default is false) }</description>
              <type>object</type>
              <is_optional>1</is_optional>
            </parameter>
          </parameters>
        </method>
        <method>
          <name>unlistenTo</name>
          <description>Allows to unlisten for a specific gesture on a dom Node.</description>
          <parameters>
            <parameter>
              <name>domNode</name>
              <description>the DOM node that listens to gesture</description>
              <type>DOM node</type>
              <is_optional>0</is_optional>
            </parameter>
            <parameter>
              <name>gesture</name>
              <description>The gesture name to unlisten</description>
              <type>string</type>
              <is_optional>0</is_optional>
            </parameter>
            <parameter>
              <name>callback</name>
              <description>The callback that was previously added (identified by { context, method })</description>
              <type>object</type>
              <is_optional>0</is_optional>
            </parameter>
          </parameters>
        </method>
      </public_methods>
    </component>
  </components>
</module>

=== sivvy/jenkins-mobile-phonegap-winktoolkit/assets/www/libs/wink/_base/ua/doc/ua.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//WAPFORUM//DTD XHTML Mobile 1.0//EN" "../../../utils/doc/wink_doc.dtd" >
<?xml-stylesheet type="text/xsl" href="../../../utils/doc/wink_doc.xsl"?>
<module>
  <title>User Agent</title>
  <name>wink.ua</name>
  <is_graphical>0</is_graphical>
  <description>
  	The ua object provides a layer of abstraction with all specifics related to the platform hosting the code.
  	It allows the user to make different implementations consistent with the platform and / or the target browser.
  </description>
  <test_pages>
    <page>
      <description>This page lists all system properties related to the client platform and browser.</description>
      <url>test_ua.html</url>
    </page>
  </test_pages>
  <compatibility>Iphone OS2, Iphone OS3, Iphone OS4, Android 1.1, Android 1.5, Android 2.1, Android 2.2, Android 2.3, BlackBerry 6, Bada 1.0</compatibility>
  <instanciation>
    <description>ua is a Literal, so it did not need to be instantiated.</description>
    <code_sample>
if (wink.ua.isIPhone)
{
	// Performs a specific IPhone process
}
    </code_sample>
  </instanciation>
  <components>
    <component>
      <name>wink.ua</name>
      <description>The ua component</description>
      <public_properties>
        <property>
          <name>isWebkit</name>
          <description>Indicates whether webkit is available</description>
          <type>boolean</type>
        </property>
        <property>
          <name>isMobile</name>
          <description>Indicates whether the platform is a mobile</description>
          <type>boolean</type>
        </property>
        <property>
          <name>isIPhone</name>
          <description>Indicates whether the platform is a IPhone</description>
          <type>boolean</type>
        </property>
        <property>
          <name>isIPod</name>
          <description>Indicates whether the platform is a IPod</description>
          <type>boolean</type>
        </property>
        <property>
          <name>isIPad</name>
          <description>Indicates whether the platform is a IPad</description>
          <type>boolean</type>
        </property>
        <property>
          <name>isIOS</name>
          <description>Indicates whether the platform is a IOS</description>
          <type>boolean</type>
        </property>
        <property>
          <name>isAndroid</name>
          <description>Indicates whether the platform is a Android</description>
          <type>boolean</type>
        </property>
        <property>
          <name>isBlackBerry</name>
          <description>Indicates whether the platform is a BlackBerry</description>
          <type>boolean</type>
        </property>
        <property>
          <name>isBada</name>
          <description>Indicates whether the platform is a Bada</description>
          <type>boolean</type>
        </property>
        <property>
          <name>isSafari</name>
          <description>Indicates whether the browser is Safari</description>
          <type>boolean</type>
        </property>
        <property>
          <name>isMozilla</name>
          <description>Indicates whether the browser is Mozilla</description>
          <type>boolean</type>
        </property>
        <property>
          <name>isOpera</name>
          <description>Indicates whether the browser is Opera</description>
          <type>boolean</type>
        </property>
        <property>
          <name>webkitVersion</name>
          <description>The webkit major version</description>
          <type>integer</type>
        </property>
        <property>
          <name>webkitMinorVersion</name>
          <description>The webkit minor version</description>
          <type>integer</type>
        </property>
        <property>
          <name>webkitUpdateVersion</name>
          <description>The webkit update version</description>
          <type>integer</type>
        </property>
        <property>
          <name>browserVersion</name>
          <description>The browser major version</description>
          <type>integer</type>
        </property>
        <property>
          <name>browserMinorVersion</name>
          <description>The browser minor version</description>
          <type>integer</type>
        </property>
        <property>
          <name>browserUpdateVersion</name>
          <description>The browser update version</description>
          <type>integer</type>
        </property>
        <property>
          <name>osVersion</name>
          <description>The OS major version</description>
          <type>integer</type>
        </property>
        <property>
          <name>osMinorVersion</name>
          <description>The OS minor version</description>
          <type>integer</type>
        </property>
        <property>
          <name>osUpdateVersion</name>
          <description>The OS update version</description>
          <type>integer</type>
        </property>
      </public_properties>
    </component>
  </components>
</module>
