=== sivvy/jenkins-mobile-phonegap-winktoolkit/assets/www/libs/wink/utils/doc/wink_doc.dtd
<!ELEMENT module ( title, name, is_graphical, description, test_pages?, compatibility, dependencies?, instanciation, components, styles? ) >

<!ELEMENT test_pages ( page+ ) >
<!ELEMENT page ( description, url ) >

<!ELEMENT dependencies ( dependency+ ) >
<!ELEMENT dependency ( module_name ) >

<!ELEMENT instanciation ( description, properties*, code_sample ) >

<!ELEMENT components ( component+ ) >
<!ELEMENT component ( name, description, public_methods*, public_properties*, events* ) >

<!ELEMENT public_methods ( method+ ) >
<!ELEMENT method ( name, description, parameters? ) >

<!ELEMENT parameters ( parameter+ ) >
<!ELEMENT parameter ( name, description, type, is_optional ) >

<!ELEMENT public_properties ( property+ ) >

<!ELEMENT properties ( property+ ) >
<!ELEMENT property ( name, description, type, is_optional? ) >

<!ELEMENT events ( event+ ) >
<!ELEMENT event ( name, description, return? ) >

<!ELEMENT return ( property+ ) >

<!ELEMENT styles ( classes ) >
<!ELEMENT classes ( class+ ) >
<!ELEMENT class ( name, description ) >

<!ELEMENT code_sample ( #PCDATA ) >
<!ELEMENT compatibility ( #PCDATA ) >
<!ELEMENT description ( #PCDATA ) >
<!ELEMENT is_graphical ( #PCDATA ) >
<!ELEMENT is_optional ( #PCDATA ) >
<!ELEMENT module_name ( #PCDATA ) >
<!ELEMENT name ( #PCDATA ) >
<!ELEMENT title ( #PCDATA ) >
<!ELEMENT type ( #PCDATA ) >
<!ELEMENT url ( #PCDATA ) >

=== sivvy/jenkins-mobile-phonegap-winktoolkit/assets/www/libs/wink/ui/xy/layer/doc/layer.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//WAPFORUM//DTD XHTML Mobile 1.0//EN" "../../../../utils/doc/wink_doc.dtd" >
<?xml-stylesheet type="text/xsl" href="../../../../utils/doc/wink_doc.xsl"?>
<module>
  <title>Layer</title>
  <name>wink.ui.xy.layer</name>
  <is_graphical>1</is_graphical>
  <description>displays a semi transparent layer you can use to build modal objects</description>
  <test_pages>
    <page>
      <description>click on the 'test' button to display the layer. click on the Layer to make it disappear. In the test page, the color and opacity of the layer have been changed</description>
      <url>test_layer.html</url>
    </page>
  </test_pages>
  <compatibility>Iphone OS2, Iphone OS3, Iphone OS4, Android 1.1, Android 1.5, Android 2.1, Android 2.2, Android 2.3, BlackBerry 6, Bada 1.0</compatibility>
  <instanciation>
    <description>
    	The layer is a literal so it doesn't need to be instantiated.
    	Use the 'show' and 'hide' method to display the layer or hide it. 
    	The layer object is part of the core so you can either use 'wink.ui.xy.layer.show()' or directly 'wink.layer.show()'.
    	The layer object is part of the core so you can either use 'wink.ui.xy.layer.hide()' or directly 'wink.layer.hide()'.
    	You can see if the layer is displayed by checking its 'visible' attribute.
    	You can also define an 'onclick' method to the layer that will be called if the user clicks on the layer (see the test page for more details)
    </description>
    <code_sample>
wink.layer.show();
wink.layer.hide();
	</code_sample>
  </instanciation>
  <components>
    <component>
      <name>wink.ui.xy.layer</name>
      <description>create, display and hide the layer</description>
      <public_methods>
        <method>
          <name>show</name>
          <description>display the layer</description>
        </method>
        <method>
          <name>hide</name>
          <description>hide the layer</description>
        </method>
        <method>
          <name>refresh</name>
          <description>update the display. Should be called in case of a change of height in the page for instance</description>
        </method>
        <method>
          <name>update</name>
          <description>update the color, opacity and zIndex of the layer. Use this method if you want to change the opacity or color or zIndex after you called the 'show' method.</description>
        </method>
      </public_methods>
      <public_properties>
        <property>
          <name>visible</name>
          <description>true if the Layer is displayed, false otherwise</description>
          <type>boolean</type>
        </property>
        <property>
          <name>color</name>
          <description>the hexa code of the layer color. The default value is #000</description>
          <type>string</type>
        </property>
        <property>
          <name>opacity</name>
          <description>opacity level of the layer between 0 and 1. The default value is 0.3</description>
          <type>float</type>
        </property>
        <property>
          <name>zIndex</name>
          <description>the hierarchical level of the layer between 0 and 999. The default value is 998</description>
          <type>integer</type>
        </property>
      </public_properties>
    </component>
  </components>
</module>

=== sivvy/jenkins-mobile-phonegap-winktoolkit/libs/wink/ui/layout/tabcontainer/doc/tabcontainer.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//WAPFORUM//DTD XHTML Mobile 1.0//EN" "../../../../utils/doc/wink_doc.dtd" >
<?xml-stylesheet type="text/xsl" href="../../../../utils/doc/wink_doc.xsl"?>
<module>
  <title>Tab Container</title>
  <name>wink.ui.layout.TabContainer</name>
  <is_graphical>1</is_graphical>
  <description>Create a tab container. You can navigate through the tabs by clicking on the arrows on each side of the tabs or directly by sliding on the tabs</description>
  <test_pages>
    <page>
      <description>The tab container contains 8 pages. Click on the button to add tags to the container. The title of the page is updated each time the user selects a new tab</description>
      <url>test_tabcontainer.html</url>
    </page>
  </test_pages>
  <compatibility>Iphone OS2, Iphone OS3, Iphone OS4, Android 1.5, Android 2.1, Android 2.2, Android 2.3, BlackBerry 6, Bada 1.0</compatibility>
  <instanciation>
    <description>To instantiate a tab container, the pages (dom nodes) MUST already be present in the page and each one MUST be defined by a unique id. Use the 'getDomNode' method to add the tab container into the page.Note that the tabs titles MUST be contained in a "a" elemnt which class name is "tc_title"</description>
    <properties>
      <property>
        <name>firstSelectedTab</name>
        <description>the index of the tab to display at the container's startup (default is item 0. 0 represents the first tab in the container)</description>
        <type>integer</type>
        <is_optional>1</is_optional>
      </property>
      <property>
        <name>displayArrows</name>
        <description>if set to 0, the right and left arrows won't be displayed (default is 1)</description>
        <type>integer</type>
        <is_optional>1</is_optional>
      </property>
      <property>
        <name>tabs</name>
        <description>An array containing the ids of the tabs to add into the tab container. The tabs dom nodes MUST be present in the page at instantiation time.</description>
        <type>array</type>
        <is_optional>0</is_optional>
      </property>
    </properties>
    <code_sample>
var properties = 
{
	'tabs': ['tab1', 'tab2', 'tab3', 'tab4', 'tab5', 'tab6', 'tab7', 'tab8'],
	'firstSelectedTab': 5
}

tabContainer = new wink.ui.layout.TabContainer(properties);
				
document.body.appendChild(tabContainer.getDomNode());
    </code_sample>
  </instanciation>
  <components>
    <component>
      <name>wink.ui.layout.TabContainer</name>
      <description>Create the tab container, creates tabs and handle tabs bar</description>
      <public_methods>
        <method>
          <name>addTab</name>
          <description>add a new tab to the tab container</description>
          <parameters>
            <parameter>
              <name>item</name>
              <description>an object containing a contentNode (containing the tab content) and a title</description>
              <type>object</type>
              <is_optional>0</is_optional>
            </parameter>
          </parameters>
        </method>
        <method>
          <name>removeTab</name>
          <description>remove a tab</description>
          <parameters>
            <parameter>
              <name>id</name>
              <description>the id of the tab to remove</description>
              <type>string</type>
              <is_optional>0</is_optional>
            </parameter>
          </parameters>
        </method>
        <method>
          <name>selectTab</name>
          <description>Select a tab</description>
          <parameters>
            <parameter>
              <name>id</name>
              <description>the id of the tab to select</description>
              <type>string</type>
              <is_optional>0</is_optional>
            </parameter>
          </parameters>
        </method>
        <method>
          <name>getDomNode</name>
          <description>returns the DOM node containing the tab container</description>
        </method>
      </public_methods>
      <public_properties>
        <property>
          <name>uId</name>
          <description>unique identifier of the component</description>
          <type>integer</type>
        </property>
        <property>
          <name>displayArrows</name>
          <description>whether te left and right arrows are displayed</description>
          <type>integer</type>
        </property>
        <property>
          <name>firstSelectedTab</name>
          <description>the index of the tab to display at the container's startup</description>
          <type>integer</type>
        </property>
        <property>
          <name>tabs</name>
          <description>the initial list of tabs of the tab container</description>
          <type>array</type>
        </property>
      </public_properties>
      <events>
        <event>
          <name>/tabcontainer/events/tabselected</name>
          <description>return the selected tabs</description>
          <return>
            <property>
              <name>id</name>
              <description>the id of the current tab</description>
              <type>string</type>
            </property>
          </return>
        </event>
      </events>
    </component>
    <component>
      <name>wink.ui.layout.TabContainer.Tab</name>
      <description>Create a tab. Tabs should only be instantiated by the TabContainer object</description>
      <public_methods>
        <method>
          <name>getContentNode</name>
          <description>returns the DOM node containing the content of the tab</description>
        </method>
        <method>
          <name>getTabNode</name>
          <description>returns the DOM node containing the tab</description>
        </method>
        <method>
          <name>activate</name>
          <description>activate the tab</description>
        </method>
        <method>
          <name>deactivate</name>
          <description>deactivate the tab</description>
        </method>
        <method>
          <name>updateMaxWidth</name>
          <description>Update the maximum width of the tab</description>
          <parameters>
            <parameter>
              <name>width</name>
              <description>the maximum width in pixels</description>
              <type>integer</type>
              <is_optional>0</is_optional>
            </parameter>
          </parameters>
        </method>
      </public_methods>
      <public_properties>
        <property>
          <name>uId</name>
          <description>unique identifier of the component</description>
          <type>integer</type>
        </property>
        <property>
          <name>id</name>
          <description>the dom node id of the tab</description>
          <type>string</type>
        </property>
        <property>
          <name>index</name>
          <description>the position of tab in the list of tabs</description>
          <type>integer</type>
        </property>
        <property>
          <name>size</name>
          <description>size in pixels of the tab</description>
          <type>integer</type>
        </property>
        <property>
          <name>position</name>
          <description>position in pixels of the tab inside the tabsNode</description>
          <type>integer</type>
        </property>
      </public_properties>
    </component>
  </components>
  <styles>
    <classes>
      <class>
        <name>tc_tabs_items</name>
        <description>The class of the itemsNode (containing the moveableNode)</description>
      </class>
      <class>
        <name>tc_tabs_moveable</name>
        <description>The class of the moveableNode (containing all the tabs)</description>
      </class>
      <class>
        <name>tc_arrow</name>
        <description>The class of the arrows (left and right)</description>
      </class>
      <class>
        <name>tc_right</name>
        <description>The class of the right arrow</description>
      </class>
      <class>
        <name>tc_bloc</name>
        <description>The class of a tab content</description>
      </class>
    </classes>
  </styles>
</module>

=== sivvy/jenkins-mobile-phonegap-winktoolkit/assets/www/libs/wink/utils/doc/wink_doc_template.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//WAPFORUM//DTD XHTML Mobile 1.0//EN" "wink_doc.dtd" >
<?xml-stylesheet type="text/xsl" href="wink_doc.xsl"?>
<module>
  <title>title</title>
  <name>name</name>
  <is_graphical>is_graphical</is_graphical>
  <description>description</description>
  <test_pages>
    <page>
      <description>description</description>
      <url>url</url>
    </page>
  </test_pages>
  <compatibility>compatibility</compatibility>
  <dependencies>
    <dependency>
      <module_name>module_name</module_name>
    </dependency>
  </dependencies>
  <instanciation>
    <description>description</description>
    <properties>
      <property>
        <name>name</name>
        <description>description</description>
        <type>type</type>
        <is_optional>is_optional</is_optional>
      </property>
    </properties>
    <code_sample>code_sample</code_sample>
  </instanciation>
  <components>
    <component>
      <name>name</name>
      <description>description</description>
      <public_methods>
        <method>
          <name>name</name>
          <description>description</description>
          <parameters>
            <parameter>
              <name>name</name>
              <description>description</description>
              <type>type</type>
              <is_optional>is_optional</is_optional>
            </parameter>
          </parameters>
        </method>
      </public_methods>
      <public_properties>
        <property>
          <name>name</name>
          <description>description</description>
          <type>type</type>
          <is_optional>is_optional</is_optional>
        </property>
      </public_properties>
      <events>
        <event>
          <name>name</name>
          <description>description</description>
          <return>
            <property>
              <name>name</name>
              <description>description</description>
              <type>type</type>
              <is_optional>is_optional</is_optional>
            </property>
          </return>
        </event>
      </events>
    </component>
  </components>
  <styles>
    <classes>
      <class>
        <name>name</name>
        <description>description</description>
      </class>
    </classes>
  </styles>
</module>

=== sivvy/jenkins-mobile-phonegap-winktoolkit/libs/wink/ux/window/doc/window.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//WAPFORUM//DTD XHTML Mobile 1.0//EN" "../../../utils/doc/wink_doc.dtd" >
<?xml-stylesheet type="text/xsl" href="../../../utils/doc/wink_doc.xsl"?>
<module>
  <title>Window</title>
  <name>wink.ux.Window</name>
  <is_graphical>0</is_graphical>
  <description>
  	The window component captures resize, scroll and orientation events and warns listeners of changes.
  </description>
  <test_pages>
    <page>
      <description>A simple test that listens to the window component events and prints the result in the web page.</description>
      <url>test_window.html</url>
    </page>
  </test_pages>
  <compatibility>Iphone OS2, Iphone OS3, Iphone OS4, Android 1.1, Android 1.5, Android 2.1, Android 2.2, Android 2.3, BlackBerry 6, Bada 1.0</compatibility>
  <instanciation>
    <description>The window component is a literal so it doesn't need to be instantiated</description>
    <code_sample>
var handleOrientation = function(properties)
{
	alert("Orientation: " + properties.orientation);
};

wink.subscribe('/window/events/orientationchange', { context: window, method: 'handleOrientation' });
    </code_sample>
  </instanciation>
  <components>
    <component>
      <name>wink.ux.window</name>
      <description>The Window component</description>
      <public_properties>
        <property>
          <name>height</name>
          <description>the height of the visible area</description>
          <type>integer</type>
        </property>
        <property>
          <name>fullWidth</name>
          <description>the width of the content</description>
          <type>integer</type>
        </property>
        <property>
          <name>fullHeight</name>
          <description>the height of the content</description>
          <type>integer</type>
        </property>
        <property>
          <name>screenWidth</name>
          <description>the width of the screen</description>
          <type>integer</type>
        </property>
        <property>
          <name>screenHeight</name>
          <description>the height of the screen</description>
          <type>integer</type>
        </property>
        <property>
          <name>orientation</name>
          <description>the orientation of the window ("horizontal" or "vertical")</description>
          <type>string</type>
        </property>
      </public_properties>
      <events>
        <event>
          <name>/window/events/resize</name>
          <description>Raised when window is resized.</description>
          <return>
            <property>
              <name>width</name>
              <description>The window width</description>
              <type>integer</type>
              <is_optional>0</is_optional>
            </property>
            <property>
              <name>height</name>
              <description>The window height</description>
              <type>integer</type>
              <is_optional>0</is_optional>
            </property>
            <property>
              <name>orientation</name>
              <description>The orientation of the window</description>
              <type>string</type>
              <is_optional>0</is_optional>
            </property>
          </return>
        </event>
        <event>
          <name>/window/events/orientationchange</name>
          <description>Raised when orientation changed.</description>
          <return>
            <property>
              <name>width</name>
              <description>The window width</description>
              <type>integer</type>
              <is_optional>0</is_optional>
            </property>
            <property>
              <name>height</name>
              <description>The window height</description>
              <type>integer</type>
              <is_optional>0</is_optional>
            </property>
            <property>
              <name>orientation</name>
              <description>The orientation of the window</description>
              <type>string</type>
              <is_optional>0</is_optional>
            </property>
          </return>
        </event>
      </events>
    </component>
  </components>
</module>

=== sivvy/jenkins-mobile-phonegap-winktoolkit/assets/www/libs/wink/ui/xy/popup/doc/popup.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//WAPFORUM//DTD XHTML Mobile 1.0//EN" "../../../../utils/doc/wink_doc.dtd" >
<?xml-stylesheet type="text/xsl" href="../../../../utils/doc/wink_doc.xsl"?>
<module>
  <title>Popup</title>
  <name>wink.ui.xy.Popup</name>
  <is_graphical>1</is_graphical>
  <description>
  	Popup is a singleton that allows to open a popup window with one (alert) or two buttons (confirm) or with a fully customizable content
  	Options are available for each type of popup style
  </description>
  <test_pages>
    <page>
      <description>A simple test that implements different use cases of the popup</description>
      <url>test_popup.html</url>
    </page>
  </test_pages>
  <compatibility>Iphone OS2, Iphone OS3, Iphone OS4, Android 1.1, Android 1.5, Android 2.1, Android 2.2, Android 2.3, BlackBerry 6, Bada 1.0</compatibility>
  <instanciation>
    <description>The popup is a singleton, it needs to be instantiated only once. No parameter is needed.</description>
    <code_sample>
var popup = new wink.ui.xy.Popup();
document.body.appendChild(popup.getDomNode());
popup.confirm({
	msg: "Do you confirm ?",
	callbackOk: { context: window, method: 'confirmOk' },
	callbackCancel: { context: window, method: 'confirmCancel' }
});
    </code_sample>
  </instanciation>
  <components>
    <component>
      <name>wink.ui.xy.Popup</name>
      <description>The Popup component</description>
      <public_methods>
        <method>
          <name>getDomNode</name>
          <description>Returns the component main dom node</description>
        </method>
        <method>
          <name>hide</name>
          <description>Hides the Popup</description>
        </method>
        <method>
          <name>alert</name>
          <description>Opens a 1-button popup with a message. calls a callback function if asked when the button is clicked</description>
          <parameters>
            <parameter>
              <name>options</name>
              <description>
                {
                  msg: the message to display,
                  btn: the text to display in the button. If nothing specified, "ok" is used,
                  callback: the callback to invoke when the user clicks on the button { context, method },
                  borderRadius: indicates whether the popup must be displayed with border-radius style,
                  duration: the duration of the display transition,
                  followScrollY: allows to follow the scroll on y-axis
                }
              </description>
              <type>object</type>
              <is_optional>0</is_optional>
            </parameter>
          </parameters>
        </method>
        <method>
          <name>confirm</name>
          <description>Opens a 2-buttons popup with a message. calls a callback function if asked, depending on the clicked button</description>
          <parameters>
            <parameter>
              <name>options</name>
              <description>
                {
                  msg: the message to display,
                  btnCancel: the text to display in the "cancel" button. If nothing specified, "cancel" is used,
                  callbackCancel: the callback to invoke when the user clicks on the 'cancel' button { context, method },
                  btnOk: the text to display in the "ok" button. If nothing specified, "ok" is used,
                  callbackOk: the callback to invoke when the user clicks on the 'ok' button { context, method },
                  borderRadius: indicates whether the popup must be displayed with border-radius style,
                  duration: the duration of the display transition,
                  followScrollY: allows to follow the scroll on y-axis
                }
              </description>
              <type>object</type>
              <is_optional>0</is_optional>
            </parameter>
          </parameters>
        </method>
        <method>
          <name>popup</name>
          <description>Opens a fully customizable popup</description>
          <parameters>
            <parameter>
              <name>options</name>
              <description>
                {
                  content: HTML code of the content,
                  arrow: position of the arrow, if needed, values: "top", "bottom", "none" (default value),
                  top: top position of the window,
                  targetNode: node pointed by the arrow (top is then ignored),
                  arrowLeftPos: left-position of the arrow,
                  borderRadius: indicates whether the popup must be displayed with border-radius style,
                  duration: the duration of the display transition,
                  followScrollY: allows to follow the scroll on y-axis,
                  layerCallback: the callback invoked when the user click on the layer, if not specified the default action is the popup hiding
                }
              </description>
              <type>object</type>
              <is_optional>0</is_optional>
            </parameter>
          </parameters>
        </method>
        <method>
          <name>preloadContent</name>
          <description>deprecated : this method is no longer needed</description>
        </method>
      </public_methods>
      <public_properties>
        <property>
          <name>uId</name>
          <description>The unique identifier of the component</description>
          <type>integer</type>
        </property>
        <property>
          <name>displayed</name>
          <description>Indicates whether the popup is displayed</description>
          <type>boolean</type>
        </property>
      </public_properties>
    </component>
  </components>
  <styles>
    <classes>
      <class>
        <name>pp_popup</name>
        <description>The class of the main DOM node</description>
      </class>
      <class>
        <name>pp_type_alert</name>
        <description>Associated to pp_popup class, it describes the alert popup</description>
      </class>
      <class>
        <name>pp_type_confirm</name>
        <description>Associated to pp_popup class, it describes the confirm popup</description>
      </class>
      <class>
        <name>pp_type_popup</name>
        <description>Associated to pp_popup class, it describes the HTML custimzable popup</description>
      </class>
      <class>
        <name>pp_hidden</name>
        <description>Associated to pp_popup class, it is used for the display status of the popup</description>
      </class>
      <class>
        <name>pp_popup_arrow</name>
        <description>The popup arrow class</description>
      </class>
      <class>
        <name>pp_bottom</name>
        <description>The popup bottom arrow specificity</description>
      </class>
      <class>
        <name>pp_top</name>
        <description>The popup top arrow specificity</description>
      </class>
      <class>
        <name>pp_none</name>
        <description>it is used for the display status of the arrow</description>
      </class>
    </classes>
  </styles>
</module>
